/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableURLRequest setValue:forHTTPHeaderField:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call -[NSMutableURLRequest setValue:forHTTPHeaderField:].
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    var value = ObjC.Object(args[2]).toString();
    var field = ObjC.Object(args[3]).toString();
    ['cookie', 'user-agent'].forEach(function (item, i) {
      if (field.toLocaleLowerCase() == item.toLocaleLowerCase()) {
        log("\tBacktrace:\n\t" + Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join("\n\t"));
      }
    })
    log('-[NSMutableURLRequest setValue:<' + value + '> forHTTPHeaderField:<' + field + '>]');
  }
}
